typedef struct {
  uint32 key;
  uint32 state;
} SIM_KEY_EVENT;

#define SIM_KEYPRESS_DOWN 0
#define SIM_KEYPRESS_UP 0

#define SIM_KEY_0 1
#define SIM_KEY_1 2
#define SIM_KEY_2 3
#define SIM_KEY_3 4
#define SIM_KEY_4 5
#define SIM_KEY_5 6
#define SIM_KEY_6 7
#define SIM_KEY_7 8
#define SIM_KEY_8 9
#define SIM_KEY_9 10
#define SIM_KEY_A 11
#define SIM_KEY_B 12
#define SIM_KEY_BACKQUOTE 13
#define SIM_KEY_BACKSLASH 14
#define SIM_KEY_BACKSPACE 15
#define SIM_KEY_C 16
#define SIM_KEY_COMMA 17
#define SIM_KEY_D 18
#define SIM_KEY_DELETE 19
#define SIM_KEY_DOWN 20
#define SIM_KEY_E 21
#define SIM_KEY_END 22
#define SIM_KEY_ENTER 23
#define SIM_KEY_EQUALS 24
#define SIM_KEY_ESC 25
#define SIM_KEY_F 26
#define SIM_KEY_G 27
#define SIM_KEY_H 28
#define SIM_KEY_HOME 29
#define SIM_KEY_I 30
#define SIM_KEY_J 31
#define SIM_KEY_K 32
#define SIM_KEY_KP_5 33
#define SIM_KEY_KP_DOWN 34
#define SIM_KEY_KP_INSERT 35
#define SIM_KEY_KP_LEFT 36
#define SIM_KEY_KP_RIGHT 37
#define SIM_KEY_L 38
#define SIM_KEY_LEFT 39
#define SIM_KEY_LEFT_BACKSLASH 40
#define SIM_KEY_LEFT_BRACKET 41
#define SIM_KEY_M 42
#define SIM_KEY_MINUS 43
#define SIM_KEY_N 44
#define SIM_KEY_O 45
#define SIM_KEY_P 46
#define SIM_KEY_PAGE_DOWN 47
#define SIM_KEY_PAGE_UP 48
#define SIM_KEY_PAUSE 49
#define SIM_KEY_PERIOD 50
#define SIM_KEY_Q 51
#define SIM_KEY_R 52
#define SIM_KEY_RIGHT 53
#define SIM_KEY_RIGHT_BRACKET 54
#define SIM_KEY_S 55
#define SIM_KEY_SEMICOLON 56
#define SIM_KEY_SINGLE_QUOTE 57
#define SIM_KEY_SLASH 58
#define SIM_KEY_SPACE 59
#define SIM_KEY_T 60
#define SIM_KEY_TAB 61
#define SIM_KEY_U 62
#define SIM_KEY_UP 63
#define SIM_KEY_V 64
#define SIM_KEY_W 65
#define SIM_KEY_X 66
#define SIM_KEY_Y 67
#define SIM_KEY_Z 68
#define SIM_KEY_SHIFT_L 69
#define SIM_KEY_SHIFT_R 70
#define SIM_KEY_CTRL_L 71
#define SIM_KEY_CTRL_R 72
#define SIM_KEY_CAPS_LOCK 73
#define SIM_KEY_WIN_L 74
#define SIM_KEY_WIN_R 75
#define SIM_KEY_ALT_L 76
#define SIM_KEY_ALT_R 77

extern CONST char *vid_key_name (uint32);
